/**
 * Holds Runtime information such as cached values for the session *
 * Created by suman on 7/1/14.
 */
Ext.define('YoutubeVideosApp.core.Session', {
        extend: 'Ext.Component',
        singleton: true,
        config: {
            //Properties... getters/setters will be generated by sencha because of Component super class
            cache: {} //Runtime cache which is cleared with each app launch
        },
        cacheIt: function (key, val) {
            this.getCache()[key] = val;
        },
        getFromCache: function (key) {
            return this.getCache()[key];
        },
        getCurrentTestUserAnswersCache: function () {
            return this.getCache()[this.getSelectedTestId() + '-UserAnswers'];
        }
    }
);